Repository mansiruhil/fail-u-forward, pull requests merged in 2025-07, with the labels that each got.

#4 Added sample .env
  .env.sample
  package-lock.json
Labels: GSSOC25, Level 1

#13 Enhanced readme.md with emojis, TOC and contact section
  readme.md
Labels: good first issue, GSSOC2025, Level 1

#12 Styled for Impact: Updated Font Color in Registration Form!
  app/register/page.tsx
Labels: GSSOC2025, Level 1, ui-ux

#24 fixed UI and made startup-page
  app/feed/page.tsx
  app/network/page.tsx
  app/profile/page.tsx
  app/topic/1/page.tsx
  components/layout/header.tsx
  components/layout/navbar.tsx
  lib/firebase.tsx
  package-lock.json
  package.json
Labels: GSSOC2025, Level 2

#26 fix: remove duplicate page.jsx file to resolve routing conflicts
  app/jobs/page.jsx
Labels: documentation, good first issue, GSSOC2025, Level 2

#27 Reapplying merged changes to trigger proper deployment
  app/feed/page.tsx
Labels: documentation, enhancement, GSSOC2025, Level 2

#33 Improved the ui of button
  app/page.tsx
Labels: GSSOC25, Level 1, ui-ux

#35 Using env in lib/firebase
  .env.sample
  app/feed/page.tsx
  lib/firebase.tsx
Labels: GSSOC25, GSSOC2025, Level 1

#77 Added CONTRIBUTING.md and linked it in README
  Contributing.md
  readme.md
Labels: enhancement, good first issue, GSSOC2025, Level 1

#105 Fix/implement post interaction buttons
  app/post/[id]/page.tsx
Labels: enhancement, GSSOC2025, Level 2, ui-ux, Feed
