Repository mansiruhil/fail-u-forward, pull requests merged in 2025-08, with the labels that each got.

#119 Added post creation and retrieval , likes, comments, dislike feature
  app/api/validate/route.ts
  app/globals.css
  components/feed/feed.tsx
  components/post/create-post.tsx
  package-lock.json
  package.json
  postcss.config.js
Labels: GSSOC2025, Level 2

#142 fixed the remove the unwanted social links
  app/notifications/page.tsx
  app/storyPage.tsx
Labels: GSSOC2025, Level 1

#145 Fixing theme by adding classes
  app/feed/page.tsx
  app/globals.css
  app/layout.tsx
  app/profile/page.tsx
  components/layout/navbar.tsx
  components/post/create-post.tsx
  components/sidebar/leftsidebar.tsx
  components/sidebar/rightsidebar.jsx
  components/theme-toggle.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/dropdown-menu.tsx
  components/ui/input.tsx
  components/ui/textarea.tsx
Labels: GSSOC2025, Level 2

#146 UI-Fixed
  app/about/page.tsx
  app/login/page.tsx
  app/page.tsx
  components/layout/navbar.tsx
Labels: GSSOC2025, Level 1

#152 Pull request for #23
  .firebaserc
  components/feed/createpost.tsx
  components/feed/feed.tsx
  firebase.json
  lib/firebase.tsx
  package-lock.json
  package.json
  route.ts
Labels: GSSOC2025, Level 2

#164 Fixed the navbar in mobile view
  components/layout/navbar.tsx
Labels: GSSOC2025, Level 1

#196 feat: add multi-language support with i18n integration
  .gitignore
  app/layout.tsx
  app/page.tsx
  components/layout/header.tsx
  components/ui/LanguageSwitcher.tsx
  i18n.ts
  next-i18next.config.js
  next.config.js
  package-lock.json
  package.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/hi/common.json
Labels: GSSOC2025, Level 2, Feature

#203 refactor(api): move business logic to service layer with standardized…
  app/api/chatbot/route.ts
  app/api/check-username/route.ts
  app/api/follow/route.ts
  app/api/news/route.ts
  app/api/post/[id]/comment/route.ts
  app/api/post/[id]/dislike/route.ts
  app/api/post/[id]/edit/route.ts
  app/api/post/[id]/like/route.ts
  app/api/post/[id]/reaction/route.ts
  app/api/post/[id]/share/route.ts
  app/api/post/route.ts
  app/api/upload/route.ts
  app/api/users/[userId]/route.ts
  app/api/validate/route.ts
  services/ai.ts
  services/follow.ts
  services/news.ts
  services/posts.ts
  services/username.ts
  services/users.ts
  services/validation.ts
Labels: GSSOC2025, Level 2
